In [214]:
import pandas as pd
import seaborn as sns
import warnings
warnings.simplefilter('ignore')
import numpy as np

In [215]:
df = pd.read_csv('application_train.csv')

In [216]:
df.sample(10)

SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
200818      390211       0         Cash loans           F            Y   
122901      300361       0         Cash loans           M            Y   
239035      434852       0         Cash loans           F            N   
160118      343504       0         Cash loans           F            Y   
34882       198478       0         Cash loans           M            Y   
142132      322791       0    Revolving loans           F            N   
90053       262400       0         Cash loans           F            N   
203160      392937       0         Cash loans           F            N   
176812      362722       0         Cash loans           F            N   
193070      381368       0         Cash loans           M            N   

       FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  \
200818               Y             1          180000.0    755190.0   
122901               N             1          216000.0    390447.0   
239035               Y             0          112500.0    545040.0   
160118               Y             1          112500.0    679500.0   
34882                Y             2          180000.0    781920.0   
142132               Y             1           67500.0    135000.0   
90053                Y             0          112500.0    343800.0   
203160               Y             1           85500.0    219069.0   
176812               Y             0          117000.0    203760.0   
193070               N             0           67500.0    239850.0   

        AMT_ANNUITY  ...  FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20  \
200818      32125.5  ...                 0                0                0   
122901      19120.5  ...                 0                0                0   
239035      25537.5  ...                 0                0                0   
160118      24403.5  ...                 0                0                0   
34882       47965.5  ...                 0                0                0   
142132       6750.0  ...                 0                0                0   
90053       12478.5  ...                 0                0                0   
203160      11313.0  ...                 0                0                0   
176812      11506.5  ...                 0                0                0   
193070      23494.5  ...                 0                0                0   

       FLAG_DOCUMENT_21 AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
200818                0                        0.0                       0.0   
122901                0                        0.0                       0.0   
239035                0                        0.0                       0.0   
160118                0                        0.0                       0.0   
34882                 0                        1.0                       1.0   
142132                0                        NaN                       NaN   
90053                 0                        0.0                       0.0   
203160                0                        0.0                       0.0   
176812                0                        NaN                       NaN   
193070                0                        0.0                       0.0   

        AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
200818                         0.0                        0.0   
122901                         0.0                        0.0   
239035                         0.0                        0.0   
160118                         0.0                        0.0   
34882                          0.0                        0.0   
142132                         NaN                        NaN   
90053                          0.0                        0.0   
203160                         0.0                        0.0   
176812                         NaN                        NaN   
193070    

In [217]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257512 entries, 0 to 257511
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(64), int64(42), object(16)
memory usage: 239.7+ MB


In [218]:
df.describe()

SK_ID_CURR         TARGET   CNT_CHILDREN  AMT_INCOME_TOTAL  \
count  257512.000000  257512.000000  257512.000000      2.575120e+05   
mean   307143.115397       0.080769       0.416509      1.684155e+05   
std     86047.050997       0.272481       0.721749      1.105872e+05   
min    157876.000000       0.000000       0.000000      2.610000e+04   
25%    232638.750000       0.000000       0.000000      1.125000e+05   
50%    307140.500000       0.000000       0.000000      1.476000e+05   
75%    381476.500000       0.000000       1.000000      2.025000e+05   
max    456255.000000       1.000000      19.000000      1.800009e+07   

         AMT_CREDIT    AMT_ANNUITY  AMT_GOODS_PRICE  \
count  2.575120e+05  257501.000000     2.572720e+05   
mean   5.988950e+05   27108.806240     5.382673e+05   
std    4.025061e+05   14480.289657     3.693680e+05   
min    4.500000e+04    1615.500000     4.050000e+04   
25%    2.700000e+05   16542.000000     2.385000e+05   
50%    5.135310e+05   24903.000000     4.500000e+05   
75%    8.086500e+05   34596.000000     6.795000e+05   
max    4.050000e+06  230161.500000     4.050000e+06   

       REGION_POPULATION_RELATIVE     DAYS_BIRTH  DAYS_EMPLOYED  ...  \
count               257512.000000  257512.000000  257512.000000  ...   
mean                     0.020882  -16039.898366   63930.692845  ...   
std                      0.013845    4364.493540  141368.981432  ...   
min                      0.000290  -25229.000000  -17912.000000  ...   
25%                      0.010006  -19689.000000   -2756.000000  ...   
50%                      0.018850  -15753.000000   -1212.000000  ...   
75%                      0.028663  -12420.000000    -288.000000  ...   
max                      0.072508   -7489.000000  365243.000000  ...   

       FLAG_DOCUMENT_18  FLAG_DOCUMENT_19  FLAG_DOCUMENT_20  FLAG_DOCUMENT_21  \
count     257512.000000     257512.000000     257512.000000     257512.000000   
mean           0.008058          0.000575          0.000505          0.000326   
std            0.089403          0.023967          0.022463          0.018058   
min            0.000000          0.000000          0.000000          0.000000   
25%            0.000000          0.000000          0.000000          0.000000   
50%            0.000000          0.000000          0.000000          0.000000   
75%            0.000000          0.000000          0.000000          0.000000   
max            1.000000          1.000000          1.000000          1.000000   

       AMT_REQ_CREDIT_BUREAU_HOUR  AMT_REQ_CREDIT_BUREAU_DAY  \
count               222727.000000              222727.000000   
mean                     0.006268                   0.006901   
std                      0.083078                   0.111287   
min                      0.000000                   0.000000   
25%                      0.000000                   0.000000   
50%                      0.000000                   0.000000   
75%                      0.000000                   0.000000   
max                      4.000000                   9.000000   

       AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
count               222727.000000              222727.000000   
mean                     0.034747                   0.266833   
std                      0.206680                   0.913544   
min                      0.000000                   0.000000   
25%                      0.000000                   0.000000   
50%                      0.000000                   0.000000   
75%                      0.000000                   0.000000   
max                      8.000000                  27.000000   

       AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
count              222727.000000               222727.000000  
mean                    0.266348                    1.903653  
std                     0.825488                    1.870100  
min                     0.000000                    0.000000  
25%              

In [219]:
df.AMT_REQ_CREDIT_BUREAU_HOUR.value_counts()

0.0    221396
1.0      1275
2.0        48
3.0         7
4.0         1
Name: AMT_REQ_CREDIT_BUREAU_HOUR, dtype: int64

In [220]:
df.AMT_REQ_CREDIT_BUREAU_DAY.value_counts()

0.0    221510
1.0      1050
2.0        89
3.0        38
4.0        23
5.0         7
6.0         7
9.0         2
8.0         1
Name: AMT_REQ_CREDIT_BUREAU_DAY, dtype: int64

In [221]:
df.AMT_REQ_CREDIT_BUREAU_WEEK.value_counts()

0.0    215505
1.0      6949
2.0       163
3.0        48
4.0        28
6.0        19
5.0         8
8.0         5
7.0         2
Name: AMT_REQ_CREDIT_BUREAU_WEEK, dtype: int64

In [222]:
df.AMT_REQ_CREDIT_BUREAU_MON.value_counts()

0.0     186108
1.0      27777
2.0       4489
3.0       1650
4.0        896
5.0        505
6.0        294
7.0        245
9.0        174
8.0        148
10.0       113
11.0        95
13.0        66
12.0        66
14.0        36
15.0        31
16.0        13
17.0        11
18.0         6
22.0         1
19.0         1
27.0         1
23.0         1
Name: AMT_REQ_CREDIT_BUREAU_MON, dtype: int64

In [223]:
df.AMT_REQ_CREDIT_BUREAU_QRT.value_counts()

0.0      180286
1.0       28410
2.0       12088
3.0        1448
4.0         402
5.0          56
6.0          25
7.0           5
8.0           5
19.0          1
261.0         1
Name: AMT_REQ_CREDIT_BUREAU_QRT, dtype: int64

In [224]:
df.AMT_REQ_CREDIT_BUREAU_YEAR.value_counts()

0.0     60047
1.0     52871
2.0     42133
3.0     28234
4.0     17340
5.0     10185
6.0      5853
7.0      3252
8.0      1773
9.0       923
12.0       26
11.0       23
10.0       18
13.0       17
14.0        9
17.0        7
15.0        4
18.0        4
19.0        4
22.0        1
20.0        1
21.0        1
16.0        1
Name: AMT_REQ_CREDIT_BUREAU_YEAR, dtype: int64

In [225]:
df.dropna(inplace= True)

In [226]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7214 entries, 25 to 257483
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(64), int64(42), object(16)
memory usage: 6.8+ MB


# Categorical Data Handling using One hot Encoding

In [227]:
object_cols = list(df.select_dtypes(include=['category','object']))

In [228]:
object_cols

['NAME_CONTRACT_TYPE',
 'CODE_GENDER',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'NAME_TYPE_SUITE',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'OCCUPATION_TYPE',
 'WEEKDAY_APPR_PROCESS_START',
 'ORGANIZATION_TYPE',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'WALLSMATERIAL_MODE',
 'EMERGENCYSTATE_MODE']

In [229]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [230]:
le = LabelEncoder()
ohe = OneHotEncoder(sparse=False)

In [249]:
label1 = le.fit_transform(df.NAME_CONTRACT_TYPE)
label1 = label1.reshape(len(label1),1)
label1.flatten()

array([1, 0, 0, ..., 0, 0, 0])

In [250]:
label2 = le.fit_transform(df.CODE_GENDER)
label2 = label2.reshape(len(label2),1)
label2.flatten()

array([0, 1, 1, ..., 0, 0, 0])

In [251]:
label3 = le.fit_transform(df.FLAG_OWN_CAR)
label3 = label3.reshape(len(label3),1)
label3.flatten()

array([0, 0, 0, ..., 0, 0, 0])

In [252]:
label4 = le.fit_transform(df.FLAG_OWN_REALTY)
label4 = label4.reshape(len(label4),1)
label4
label_ohe4 = ohe.fit(label4)
label_ohe4_new  = label_ohe4.transform(label4)
label_ohe4_new.flatten()

array([0., 1., 0., ..., 1., 0., 1.])

In [253]:
label5 = le.fit_transform(df.NAME_TYPE_SUITE)
label5= label5.reshape(len(label5),1)
label5
label_ohe5 = ohe.fit(label5)
label_ohe5_new  = label_ohe5.transform(label5)
label_ohe5_new.flatten()

array([0., 0., 0., ..., 0., 0., 1.])

In [254]:
label6 = le.fit_transform(df.NAME_INCOME_TYPE)
label6 = label6.reshape(len(label5),1)
label6
label_ohe6 = ohe.fit(label6)
label_ohe6_new  = label_ohe6.transform(label6)
label_ohe6_new.flatten()

array([1., 0., 0., ..., 1., 0., 0.])

In [255]:
label7 = le.fit_transform(df.NAME_EDUCATION_TYPE)
label7 = label7.reshape(len(label7),1)
label_ohe7_new = ohe.fit_transform(label7)
label_ohe7_new.flatten()

array([0., 1., 0., ..., 0., 0., 1.])

In [256]:
label8 = le.fit_transform(df.NAME_FAMILY_STATUS)
label8 = label8.reshape(len(label8),1)
label_ohe8_new = ohe.fit_transform(label8)
label_ohe8_new.flatten()

array([0., 1., 0., ..., 0., 0., 0.])

In [257]:
label9 = le.fit_transform(df.NAME_HOUSING_TYPE)
label9 = label9.reshape(len(label9),1)
label9
label_ohe9 = ohe.fit(label9)
label_ohe9_new  = label_ohe9.transform(label9)
label_ohe9_new.flatten()

array([0., 1., 0., ..., 0., 0., 0.])

In [258]:
label10= le.fit_transform(df.OCCUPATION_TYPE)
label10 = label10.reshape(len(label10),1)
label10
label_ohe10 = ohe.fit(label10)
label_ohe10_new  = label_ohe10.transform(label10)
label_ohe10_new.flatten()

array([1., 0., 0., ..., 0., 0., 0.])

In [259]:
label11 = le.fit_transform(df.WEEKDAY_APPR_PROCESS_START)
label11 = label11.reshape(len(label11),1)
label11
label_ohe11 = ohe.fit(label11)
label_ohe11_new  = label_ohe11.transform(label11)
label_ohe11_new.flatten()

array([0., 1., 0., ..., 1., 0., 0.])

In [260]:
label12 = le.fit_transform(df.ORGANIZATION_TYPE)
label12 = label12.reshape(len(label12),1)
label12
label_ohe12 = ohe.fit(label12)
label_ohe12_new  = label_ohe12.transform(label12)
label_ohe12_new.flatten()

array([0., 0., 0., ..., 0., 0., 0.])

In [261]:
label13 = le.fit_transform(df.FONDKAPREMONT_MODE)
label13 = label13.reshape(len(label13),1)
label13
label_ohe13 = ohe.fit(label13)
label_ohe13_new  = label_ohe13.transform(label13)
label_ohe13_new.flatten()

array([0., 0., 1., ..., 0., 0., 0.])

In [268]:
label14 = le.fit_transform(df.HOUSETYPE_MODE)
label14 = label14.reshape(len(label14),1)
label14
label_ohe14 = ohe.fit(label14)
label_ohe14_new  = label_ohe14.transform(label14)
label_ohe14_new.flatten()

array([1., 0., 0., ..., 1., 0., 0.])

In [263]:
label15 = le.fit_transform(df.WALLSMATERIAL_MODE)
label15 = label15.reshape(len(label15),1)
label15
label_ohe15 = ohe.fit(label15)
label_ohe15_new  = label_ohe15.transform(label15)
label_ohe15_new.flatten()

array([0., 0., 0., ..., 0., 0., 0.])

In [264]:
label16 = le.fit_transform(df.EMERGENCYSTATE_MODE)
label16 = label16.reshape(len(label16),1)
label16
label_ohe16 = ohe.fit(label16)
label_ohe16_new  = label_ohe16.transform(label16)
label_ohe16_new.flatten()

array([1., 0., 1., ..., 0., 1., 0.])

In [265]:
df = df.join(pd.DataFrame({'label1':label1,
                           'label2':label2,
                           'label3':label3,
                           'label_ohe4_new':label4,
                           'label_ohe5_new':label5,
                           'label_ohe6_new':label6,
                           'label_ohe7_new':label7,
                           'label_ohe8_new':label8,
                           'label_ohe9_new':label9,
                           'label_ohe10_new':label10,
                           'label_ohe11_new':label11,
                           'label_ohe12_new':label12,
                           'label_ohe13_new':label13,
                           'label_ohe14_new':label14,
                           'label_ohe15_new':label15,
                           'label_ohe16_new':label16 },index=[0]))

Exception: Data must be 1-dimensional

In [266]:
df.head()

SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
25       157905       0    Revolving loans           F            Y   
38       157921       0         Cash loans           M            Y   
41       157925       0         Cash loans           M            Y   
87       157983       0         Cash loans           F            Y   
112      158017       0    Revolving loans           F            Y   

    FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
25                Y             0          270000.0    810000.0      40500.0   
38                Y             0          198000.0    904500.0      26577.0   
41                Y             0          144000.0    381528.0      24534.0   
87                N             1          117000.0    675000.0      21906.0   
112               Y             0          144000.0    157500.0       7875.0   

     ...  FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
25   ...                 0                0                0                0   
38   ...                 0                0                0                0   
41   ...                 0                0                0                0   
87   ...                 0                0                0                0   
112  ...                 0                0                0                0   

    AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
25                         0.0                       0.0   
38                         0.0                       0.0   
41                         0.0                       0.0   
87                         0.0                       0.0   
112                        0.0                       0.0   

     AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
25                          0.0                        2.0   
38                          0.0                        0.0   
41                          0.0                        0.0   
87                          0.0                        0.0   
112                         0.0                        1.0   

     AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
25                         0.0                         0.0  
38                         1.0                         2.0  
41                         0.0                         3.0  
87                         0.0                         2.0  
112                        0.0                         3.0  

[5 rows x 122 columns]